### ISSUE TITLE
Disable syntax highlighting when editing code

### ISSUE THREAD

**Issue by giucu91** [WPChill/modula-lite#507] opened 2021-02-15 12:38 UTC
**Describe the bug**
In profile you have the option to disable syntax highlighting when editing code if this option is checked the gallery dasboard will not work.

**Expected behavior**
If this option is checked we need to stop addding the Visual CSS textarea. We will leave a simple textarea.

**Screenshots**
![image](https://user-images.githubusercontent.com/7580330/107947525-27022c80-6f9b-11eb-8c70-b27cc5d6532a.png)
![image](https://user-images.githubusercontent.com/7580330/107947640-544eda80-6f9b-11eb-9705-fd10c5bb3f6a.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by razvanaldea89** [comment] 2021-09-16 08:49
Duplicate of https://github.com/WPChill/modula-lite/issues/586 . Will close this

**Closed by razvanaldea89** 2021-09-16 08:49 UTC
Labels: bug, next-update
