### ISSUE TITLE
Resize window not working well

### ISSUE THREAD

**Issue by ViSi19** [WPChill/modula-lite#451] opened 2020-11-11 12:36 UTC
**Describe the bug**
https://drive.google.com/file/d/1ntGT_iz9PDqFkAaBkK1KNW3mjhIBCmGr/view

**Comment by cristianraiber** [comment] 2021-01-03 12:52
This is regarding the "Columns grid"

**Comment by razvanaldea89** [comment] 2021-01-07 07:53
Can't reproduce this either ( neither did @Florin415 ). @andyluak test it on Safari please and let us know? Maybe was solved in the meantime

**Comment by andyluak** [comment] 2021-01-07 08:00
@razvanaldea89 @Florin415 tested on safari it works . I think this issue was fixed on a previous issue with the resize senzor and we probably missed checking this one too .

**Closed** 2021-02-03 13:55 UTC
Labels: bug, can't replicate, medium-priority, tested
