### ISSUE TITLE
Social share information

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#326] opened 2020-03-09 15:25 UTC
When sharing an image ( social icon is on image ) it gets the page title. Maybe we should share the image caption/description and not the page title.

**Comment by cristianraiber** [comment] 2020-03-09 15:31
+1 for image title.

**Comment by cristianraiber** [comment] 2020-03-10 11:27
And maybe we can also include the caption as the "text" that gets shared with the photo?

**Comment by cristianraiber** [comment] 2020-08-27 11:04
Duplicate of #303

**Comment by Florin415** [comment] 2021-01-12 14:33
When use the Share link on twitter from the front it will add the caption in front of the link :https://gyazo.com/88769b91a935ede08925f8b6afd4913e . In lightbox it will not do this :   https://gyazo.com/f23ebab6f7a5aa142bc956c28948d24d

**Closed** 2021-02-03 14:04 UTC
Labels: enhancement, medium-priority, tested
