### ISSUE TITLE
 Scaled images w/srcset

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#475] opened 2021-01-11 13:22 UTC
**Describe the bug**
https://wordpress.org/support/topic/scaled-images-w-srcset/

**To Reproduce**
I tried this for a brief minute on the live site, and then reproduced it on my local, clean, WordPress test install w/Twenty Twenty:

1. I uploaded six images to the test site that are also shared with my live site.
2. I created an all-new Modula gallery with these six images, and the thumbnail size set to 150.
3. I dumped the gallery into a clean test post, and the the 300×300 versions came up in the src as they should.
4. I then went into …wp-admin/options.php ant set the upload_url_path to https://media.bikesharemuseum.com.
5. Checked the inspector; src now defaults to the full-size image.

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.1

**Comment by razvanaldea89** [comment] 2021-02-08 12:39
Duplicate of #228

**Closed** 2021-02-08 14:52 UTC
Labels: bug, duplicate
