### ISSUE TITLE
compatibility with meow lightbox

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#575] opened 2021-05-31 06:23 UTC
**Is your feature request related to a problem? Please describe.**
Problem and solution described here:
https://secure.helpscout.net/conversation/1515125831/38036?folderId=1289779

**Comment by cudak888** [comment] 2021-06-30 06:11
FYI, the solution on HelpScout can't be seen for anyone who doesn't have access to that conversation.

Would like to implement this workaround.

**Comment by jordymeow** [comment] 2021-07-02 00:00
Hi,

This is why I replied to the customer on HelpScout:

In fact, Meow Lightbox looks for he wp-image-{id} in the class attributes of the img element. Based on that, it retrieves the information for this image. I know it's quite specific, but by default it works this way with WordPress, since 4.9 or so.

I noticed you might use the data-image-id attribute in the text to that image, but would it be possible to add the class I am looking for, or maybe, at least, a data-image-id directly in the image? If yes, I could definitely add support for it :) But I think the class would be better.

**Comment by cristianraiber** [comment] 2021-07-02 14:00
> FYI, the solution on HelpScout can't be seen for anyone who doesn't have access to that conversation.
> 
> Would like to implement this workaround.
> 
> EDIT: This thread isn't available even to logged in users:
> 
> "The mailbox you requested is not available
> You may not have permission to view this mailbox, or it no longer exists."

That's actually on purpose. A solution will be implemented and released publicly shortly.

**Comment by cudak888** [comment] 2021-07-03 03:17
Good to hear! 

I was on the verge of creating some hack jQuery to pull the ID and inject it into the HTML (!)

**Comment by cudak888** [comment] 2021-10-31 21:55
Any updates?

**Comment by jordymeow** [comment] 2021-10-31 22:01
Nothing from my side; I suggested that the wp-image-{id} class was added, as it would resolve everything. The fact it's not present actually proves that this plugin doesn't go through the standard WordPress process to display images. I believe it might be outdated and it doesn't look like there were updates for quite some time.

**Comment by cristianraiber** [comment] 2021-11-01 08:10
> Nothing from my side; I suggested that the wp-image-{id} class was added, as it would resolve everything. The fact it's not present actually proves that this plugin doesn't go through the standard WordPress process to display images. I believe it might be outdated and it doesn't look like there were updates for quite some time.

You're just looking in the wrong plages, @jordymeow. Last plugin update was released 4 weeks ago and we've got another one in the pipeline. If you plan on just assuming things without doing any bit of research work, you're not actually helping anyone. 

Hard to say your intention was actually one of a person trying to be helpful, but, alas, I'll make sure to prioritise this. Thanks for taking the time to try and swerve users from Modula onto Meow - so much about "caring about the community".

**Comment by jordymeow** [comment] 2021-11-01 08:42
> Last plugin update was released 4 weeks ago and we've got another one in the pipeline. If you plan on just assuming things without doing any bit of research work, you're not actually helping anyone.

What I said is simply based on the status of this repo - there are many opened issues, no solution for this one, and the code here wasn't updated for over a year. You shouldn't blame me for not looking further; why would I? This looks like the code for the plugin this user is using (and he is here too, after all).

> Thanks for taking the time to try and swerve users from Modula onto Meow

My reply was only stating facts. Nothing more. You should probably take it a bit easier, as I didn't try anything.

Truth is that you should probably close this repo, and let your users go to the _right_ place naturally. That would be easier for them, for me and save you from feeling annoyed by facts :)

**Comment by cristianraiber** [comment] 2021-11-01 10:12
> What I said is simply based on the status of this repo - there are many opened issues, no solution for this one, and the code here wasn't updated for over a year. You shouldn't blame me for not looking further; why would I? This looks like the code for the plugin this user is using (and he is here too, after all).

That's what happens with a popular product - you get more opened issues. Feel free to check other repositories as well, and see how many open issues there are. On the contrary - a popular repo will have many active opened issues, instead of less. 

When I said "research", I assumed you at least know how to use GitHub and look at commit history. My bad for assuming that. 

> My reply was only stating facts. Nothing more. You should probably take it a bit easier, as I didn't try anything.

Made up facts, nonetheless. Unbiased opinions are appreciated, personal opinions - keep them for yourself. This is not your public venting place / forum. If you've got a personal opinion, feel free to DM me or hit me up on Twitter and I might read it. 

> Truth is that you should probably close this repo, and let your users go to the _right_ place naturally. That would be easier for them, for me and save you from feeling annoyed by facts :)

Calling your product "the right place" is an overstatement and you're still missing the point. You're making bold claims without anything to back those claims up. It's like you're trying, on purpose, to stir up a fight. 

 ⚠️ Please keep this civil and refrain yourself from un-necessary commentary. I'll keep your comments publicly available, but if you keep it up, I won't have any other solution but to start editing out the parts that don't belong in a GitHub repo.

**Comment by jordymeow** [comment] 2021-11-01 10:59
> Made up facts, nonetheless.

As a reminder, I only said this: _I believe it might be outdated and it doesn't look like there were updates for quite some time._ Pay attention to the "I believe" and "it doesn't look like". I was even being cautious. Looking at this repo, nothing much happened - maybe a few merges and version bumps. Not sure why I would DM you or anything, I don't know who you are. 

You also mentioned that I should have made a research (ok...), as it seems things are happening somewhere else for this plugin. Which is why I mentioned about potentially closing this repo so that people go to _the right place_. That would be cleaner and simpler.

> Calling your product "the right place" 

I was not talking about my product, obviously (did I ever mention the name of it, or anything?). Honestly, I feel a bit disturbed that you come so easily to this kind of conclusion.

And I believe I was civil. 

Cheers and best of luck with everything.

**Comment by cudak888** [comment] 2021-11-01 12:39
I can understand a plugin developer not prioritizing a compatibility issue with another plugin - brought forth by a single user - for six months. I completely get it. What more can one ask from the free version of the plugin? (For that matter, purchase of the full version isn't a license to demand one's whims from the developer either).

However, I _don't_ care for it when plugin's developers can't work out a disagreement (or misunderstanding, as it seems here). It also disturbs me to think that one of my long-term unconfirmed fears was true: That even some of the better Wordpress plugin developers would rather compete against each other rather than work together to mutually strengthen each other's products. 

I may be only one user, but from my POV, this conversation reflects particularly poorly on the Modula team. I realize Jordy's initial comment could have upset a small team of coders working on their own product, but it wasn't an outright attack - and would have been better suited to an opportunity to resolve the difference, rather than further any antagonism.

That said, I see no reason why there's even a reason to one-upmanship each other's gallery plugins. Even though I really like Modula _and_ Meow products, you both have unique products that aren't really as interchangeable as you're pitting them. Meow Gallery doesn't have quite features I'm seeking, and - in my eyes - I see an opportunity for both in the market. 

I was perfectly willing to be patient because of the exceptional functionality of the Modula plugin and the courtesy of the staff in my previous emails, but after this, I think I'll look somewhere else entirely.

**Comment by cristianraiber** [comment] 2021-11-01 13:16
@cudak888 - thanks for pitching in, highly appreciate the feedback. FWIW - this will be released sometime next month. 

I might have over-reacted and for that, I'm sorry @jordymeow. 

If you're not happy with Modula, I totally understand that. I totally understand if you don't wish to wait for this to be released. Totally up to you.

I will be closing the comments on this.

**Comment by cudak888** [comment] 2021-11-01 21:03
Perhaps even I have a bit of an apology to make for getting a bit too testy with my last comment there.

That's really quite excellent (_cue Bill & Ted air guitar_) news @cristianraiber. Even though I was willing to hunt for an alternative, I really don't want to. Modula works exceptionally well for my site ((bikesharemuseum.com)), and I love @jordymeow's lightbox equally - enough so that I've felt it's been worth the wait. Since the Museum isn't a non-profit, but something I fund on my own, I have the luxury of time with it. Honestly, I've literally just avoided updating it for six months and have taken a break for other projects!

Modula is also pretty integrated into the theme too, with the gallery on each bike page running off a custom field entry, using the Modula gallery number. While I did consider it, I still think it's much easier to wait for the fix that allows for the best of both plugins, rather than recreate a fair number of galleries _and_ redesign most of the site just to fit something else in that will never be as good as these two plugins combined.

**Comment by cristianraiber** [comment] 2021-11-02 08:09
@cudak888 - a commit has already been pushed that addresses the issue reported by @jordymeow 

It'll be included in our next Modula update

**Closed** 2022-02-18 09:47 UTC
Labels: need testing, medium-priority, compatibility
