### ISSUE TITLE
PHP 8 Upgrade Errors

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#776] opened 2023-02-14 09:22 UTC
**Describe the bug**
After upgrading to PHP 8, we are receiving many Warnings (that are oddly appearing in the “Product Feed Information” section on the edit product page within the GPF (Google Product Feed Plugin) that read:

Warning: Array to string conversion in /public_html/wp-content/plugins/modula-best-grid-gallery/includes/libraries/class-gamajo-template-loader.php on line 112

There are 50+ of these warnings

https://wordpress.org/support/topic/php-8-upgrade-errors/

**Comment by TeoAlex** [comment] 2023-02-20 10:01
The issue was happening due to the fact that GPF is using an older version of [Gamajo template loader](https://github.com/WPChill/modula-lite/blob/2.7.2/includes/libraries/class-gamajo-template-loader.php) than us and called a method incorrectly. The issue is fixed in newer versions of GPF

**Closed by TeoAlex** 2023-02-20 10:01 UTC
Labels: bug
