### ISSUE TITLE
images are on top of each other in Elementor

### ISSUE THREAD

**Issue by mplusb** [WPChill/modula-lite#468] opened 2020-12-16 14:40 UTC
**Describe the bug**
when you add the Modula widget in Elementor editor it stacks images one on top of the other.
It should look like this: https://gyazo.com/1e540a78e502a1775ba26b19210524cc
But it looks like this: https://gyazo.com/5e013be24761b8537ba03c38744128af

**To Reproduce**
Go to Pages > edit with Elementor > add Modula widget > see issue

* Which addons do you have installed: 
- [x] Modula PRO
- [x] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [x] Watermark
- [ ] Deeplink
- [x] Right-Click Protection
- [x] Advanced Shortcode
- [x] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [x] Chrome - on my end seems to happen only on Chrome, but the client says it's the same no matter the browser. Should check all.
- [ ] Firefox
- [ ] Safari
- [ ] Other 

#### Used versions
* WordPress version: 5.6
* Modula Lite version: 2.4.1
* Modula PRO version: 2.4.2
* Albums version: -1.0.7
* Watermark version: -1.0.3
* Right-Click Protection version: -1.0.5
* Advanced Shortcode version: -1.0.2
* SpeedUp version: -1.0.6

**Comment by Florin415** [comment] 2020-12-17 09:56
I tested this and indeed there seems to be a problem , on mozila firefox it will work properly but on chrome it will not as you can see in these screenshots : 
Chrome : https://prnt.sc/w4k612
Opera:https://prnt.sc/w4kasl
Edge : https://prnt.sc/w4kbha
Mozilla : https://prnt.sc/w4k9yd

Also there seems to be a problem in Modula Albums : 
Chrome : https://prnt.sc/w4klrw
Firefox : https://prnt.sc/w4kmav

Used all the above plugins from : https://wp-modula.com/

**Comment by razvanaldea89** [comment] 2020-12-17 15:03
This seems to be an issue with the jQuery Migrate. Tested with jQuery Migrate Helper plugin and seems to work fine.

**Comment by Florin415** [comment] 2020-12-18 09:12
To achieve this temporary solution mentioned by @razvanaldea89 , after you install the plugin go to https://prnt.sc/w582wn and choose https://prnt.sc/w5838b

**Comment by cristianraiber** [comment] 2020-12-18 09:15
@razvanaldea89 - we shouldn't be relying on jQuery Migrate Helper. We should fix our own product. cc @giucu91

**Comment by razvanaldea89** [comment] 2020-12-18 13:02
@cristianraiber was trying to tell about the source of the problem. That is for sure not a solution, we should fix it

**Comment by giucu91** [comment] 2020-12-18 15:19
@razvanaldea89 jQuery Migrate is bundle in WP 5.6 so installing jQuery Migrate Helper wont fix the problem.

The problem is this : https://github.com/elementor/elementor/issues/6756

The solution is this : https://github.com/metafizzy/flickity/pull/900/files

**Comment by Florin415** [comment] 2021-01-07 14:42
Tested with Modula lite + Elementor now it's working . I tried to see if it works with albums as well but could not create albums for the moment and I opened for that this issue : https://github.com/WPChill/modula-lite/issues/473

**Closed** 2021-02-04 07:02 UTC
Labels: bug, medium-priority, tested
