### ISSUE TITLE
Image Save Folder

### ISSUE THREAD

**Issue by vagu71** [WPChill/modula-lite#278] opened 2020-01-28 16:29 UTC
The images get saved in uploads in the month in which the plugin was installed. Not in the latest current month folder.

**Comment by andyluak** [comment] 2020-02-21 12:01
@giucu91 can confirm this happens .

**Comment by razvanaldea89** [comment] 2021-01-11 09:39
Changed date and time for laptop/server but it seems it uploads in the corresponded month. Tested now with date changed to may this year:
![image](https://user-images.githubusercontent.com/44024114/104165111-9c5d6900-5401-11eb-88b9-6dd90356f5f9.png)

**Comment by Florin415** [comment] 2021-01-14 16:22
Could not reproduce the issue, installed Modula, added photos to a gallery, changed date/time to computer, added some more photos to gallery + made another gallery . The first added photos before the changed date/time to computer it added them to the current date/time folder , the other ones to the one selected for my computer as you will be able to see in this video : https://drive.google.com/file/d/1Hz4XBSbNE5Ky_6nf9cR7X8d5urdQp_Kt/view

**Comment by cristianraiber** [comment] 2021-01-14 19:20
Will be closing this.

**Closed by cristianraiber** 2021-01-14 19:20 UTC
Labels: bug, can't replicate, medium-priority, tested
