### ISSUE TITLE
Notice is not placed correctly

### ISSUE THREAD

**Issue by razvanaldea89** [WPChill/modula-lite#606] opened 2021-09-27 18:45 UTC
**Describe the bug**
Notice for rating is not placed correctly. 

**To Reproduce**
Reset the installation / uninstall and wait for review request

**Expected behavior**

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/44024114/134966877-2b5f662d-2e08-4516-a95b-a10c9e9a4dc7.png)

* Which addons do you have installed: 
- [ ] Modula PRO
- [ ] Albums
- [ ] Slider
- [ ] Lightbox Slideshow
- [ ] Password Protect
- [ ] Watermark
- [ ] Deeplink
- [ ] Right-Click Protection
- [ ] Advanced Shortcode
- [ ] SpeedUp
- [ ] Video

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile
- [ ] Other 

#### Used versions
* WordPress version: 
* Modula Lite version: 
* Modula PRO version: -
* Albums version: -
* Slider version: -
* Lightbox Slideshow version: -
* Password Protect version: -
* Watermark version: -
* Deeplink version: -
* Right-Click Protection version: -
* Advanced Shortcode version: -
* SpeedUp version: -
* Video version: -

**Comment by giucu91** [comment] 2021-12-08 07:27
duplicate of #617

**Closed by giucu91** 2021-12-08 07:27 UTC
Labels: bug
