### ISSUE TITLE
Warning undefined variable when image size is set to full

### ISSUE THREAD

**Issue by cristinnaiulia** [WPChill/modula-lite#963] opened 2024-05-31 09:20 UTC
Settings:
![Screenshot 2024-05-31 122003](https://github.com/WPChill/modula-lite/assets/63049546/930f77af-6733-49bd-a057-26ac9e08df1d)

Warning:
![Screenshot 2024-05-31 121828](https://github.com/WPChill/modula-lite/assets/63049546/79c4e69f-b5b8-4308-8ff9-48b5ca90e9ce)

**Comment by TeoAlex** [comment] 2024-07-16 08:44
Could not reproduce the issue. It was most likely fixed in a recent update of Modula SLider

**Closed** 2024-07-18 08:31 UTC
Labels: bug, tested
